# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "CertWarden client for Home Assistant"
  org.opencontainers.image.description: "CertWarden client add-on to retrieve and renew certs for Home Assistant from local CertWarden service (https://www.certwarden.com)"
  org.opencontainers.image.source: "https://github.com/Sherd21/ha-addons/"
  org.opencontainers.image.licenses: "Apache License 2.0"
