# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: CertWarden client for Home Assistant (new)
version: "0.0.9"
slug: certwarden1
description: CertWarden client add-on to retrieve and renew certs for Home Assistant from local CertWarden service (https://www.certwarden.com)
url: "https://github.com/Sherd21/ha-addons/tree/main/certwarden-ha-client"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - ssl:rw
ports:
  5055/tcp: 5055
options:
  server: null
  server_communication_key: null
  certificate_name: null
  key_name: null
  certificate_apikey: null
  key_apikey: null
schema:
  server: 'match(^https:\/\/[^\s\/$.?#].[^\s]*$)'
  server_communication_key: password
  certificate_name: str
  key_name: str
  certificate_apikey: password
  key_apikey: password
